---
title: "Scratch Variability"
author: "Dr. Williams"
date: "2/20/2022"
output: html_document
---

```{r}
library(tidyverse)
library(randomNames)
```


```{r}
## 5 to 10 names
n = 5

## 1) Generate Data: GPA and Names
gpa_vec = round(rnorm(n,3.25,0.3),3)
name_vec = randomNames(n,ethnicity = 5) %>% 
  word(2) 
id_vec = 1:n
gpa_df = data.frame(id_vec,name_vec,gpa_vec)


## 2) Calculate Mean of GPA
mean_gpa = mean(gpa_vec)

```


```{r}
## 3) Plot just GPAs 
gpa_df %>% 
  ggplot(aes(x = id_vec, y = gpa_vec)) +
  geom_point(size = 4) +
  labs(x = 'The Students', y = 'GPA',title = 'GPAs Across the Class') + 
  scale_x_continuous(breaks = 1:5,
                   labels = name_vec) +
  theme_bw() +
  theme(plot.title = element_text(size = 20, face = 'bold',hjust = 0.5),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 12.5, color = 'black'))

```



```{r}
## 4) Plot just GPAs 
p1 +
  geom_hline(yintercept = mean_gpa, size = 2, color = 'red') +
  geom_text(x = (n+1)/2, y = mean_gpa +0.1, label = 'GPA Mean', size = 6, color = 'red')
```